before_script:
  - 'which ssh-agent || ( apk add --update openssh-client )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - touch ~/.ssh/known_hosts
  - cd ~/.ssh
  - cat $SSH_PRIVATE_KEY > id_rsa
  - chmod 400 id_rsa
  - chmod 644 ~/.ssh/known_hosts

deploy_testing:
  script:
    - ssh-keyscan -t rsa 49.12.245.100 >> ~/.ssh/known_hosts
    - ssh -i ~/.ssh/id_rsa curiexr@49.12.245.100 "cd /home/curiexr/myprojectdir/myprojectdir && git pull origin testing && docker-compose build && docker-compose up -d"
  only:
    - testing

deploy_production:
  script:
    - ssh-keyscan -t rsa 78.47.214.4 >> ~/.ssh/known_hosts
    - ssh -i ~/.ssh/id_rsa curiexr@78.47.214.4 "cd /home/curiexr/myprojectdir/myprojectdir && git pull origin main && docker-compose build && docker-compose up -d"
  only:
    - main
