version: '3.2'

volumes:
  postgresql_quiz_data-new: {}

services:
  db:
    image: postgres:latest
    container_name: quiz-db
    restart: always
    volumes:
      - postgresql_quiz_data-new:/var/lib/postgresql/data
    env_file:
      - ./.env
  django:
    container_name: quiz-django
    image: quiz-django:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - quiz-django:latest
    restart: always
    command: /start-django
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
    - 8080:8000
